# Generated by Django 4.2.2 on 2023-06-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('num_chassi', models.CharField(max_length=255)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='core.marque')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='core.modele')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voitures/')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('en attente', 'en attente'), ('validé', 'validé'), ('retiré', 'retiré')], default=('en attente', 'en attente'), max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='core.voiture')),
            ],
        ),
    ]
