# Generated by Django 4.2.2 on 2023-06-20 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('marque', models.CharField(max_length=255)),
                ('num_chassi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voitures/')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('en attente', 'en attente'), ('validé', 'validé'), ('retiré', 'retiré')], default=('en attente', 'en attente'), max_length=255)),
                ('montant', models.IntegerField()),
                ('propriétaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='core.voiture')),
            ],
        ),
    ]
